<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateSectionsTable extends Migration
{

    public function up()
    {
        Schema::create('sections', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 500);
            $table->text('description')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });

        DB::statement("

            INSERT INTO `sections` (`name`) VALUES 
           ( 'PRODUCTS OF THE CHEMICAL OR ALLIED INDUSTRIES'), 
            ( 'PLASTICS AND ARTICLES THEREOF, RUBBER AND ARTICLES THEREOF '), ( 'RAW HIDES AND SKINS, LEATHER, FURSKINS AND ARTICLES THEREOF, SADDLERY AND HARNESS, TRAVEL GOODS, HANDBAGS AND SIMILAR CONTAINERS, ARTICLES OF ANIMAL GUT (OTHER THAN SILK-WORM GUT) '),
            ( 'WOOD AND ARTICLES OF WOOD, WOOD CHARCOAL, CORK AND ARTICLES OF CORK,MANUFACTURES OF STRAW, OF ESPARTO OR OF OTHER PLAITING MATERIALS, BASKETWARE AND WICKERWORK  '),
            ( 'PULP OF WOOD OR OF OTHER FIBROUS CELLULOSIC MATERIAL, WASTE AND SCRAP OF PAPER OR PAPERBOARD,
            PAPER AND PAPERBOARD AND ARTICLES THEREOF '), 
            ( 'TEXTILES AND TEXTILE ARTICLES  '), ( 'FOOTWEAR, HEADGEAR, UMBRELLAS, SUN UMBRELLAS, WALKING-STICKS,
            SEAT-STICKS, WHIPS, RIDING-CROPS AND PARTS THEREOF,
            PREPARED FEATHERS AND ARTICLES MADE THEREWITH,
            ARTIFICIAL FLOWERS, ARTICLES OF HUMAN HAIR
            '),( 'ARTICLES OF STONE, PLASTER, CEMENT, ASBESTOS, MICA OR SIMILAR MATERIALS,
            CERAMIC PRODUCTS, GLASS AND GLASSWARE '), ( 'NATURAL OR CULTURED PEARLS, PRECIOUS OR SEMI-PRECIOUS STONES, PRECIOUS METALS,
            METALS CLAD WITH PRECIOUS METAL AND ARTICLES THEREOF,
            IMITATION JEWELLERY, COIN '), ( 'BASE METALS AND ARTICLES OF BASE METAL  '), ( 'MACHINERY AND MECHANICAL APPLIANCES, ELECTRICAL EQUIPMENT, PARTS THEREOF,
            SOUND RECORDERS AND REPRODUCERS, TELEVISION IMAGE AND SOUND RECORDERS
            AND REPRODUCERS, AND PARTS AND ACCESSORIES OF SUCH ARTICLES
            '), ( 'VEHICLES, AIRCRAFT, VESSELS AND ASSOCIATED TRANSPORT EQUIPMENT  '),
            ( 'OPTICAL, PHOTOGRAPHIC, CINEMATOGRAPHIC, MEASURING, CHECKING, PRECISION,
            MEDICAL OR SURGICAL INSTRUMENTS AND APPARATUS, CLOCKS AND WATCHES,
            MUSICAL INSTRUMENTS, PARTS AND ACCESSORIES THEREOF  '),
            ( 'ARMS AND AMMUNITION, PARTS AND ACCESSORIES THEREOF  '),
            ( 'MISCELLANEOUS MANUFACTURED ARTICLES  '),
            ( 'WORKS OF ART, COLLECTORS PIECES AND ANTIQUES  ')


            ");
    }

    public function down()
    {
        Schema::dropIfExists('sections');
    }
}
